// ====================================================================
// GEOSYNC - REAL EMPLOYEE & ATTENDANCE DOMAIN MODEL (30 KARYAWAN REAL)
// Struktur data lengkap 30 Karyawan Real Indonesia dengan persistensi JSON.
// CATATAN KEAMANAN: Field `password` telah dihapus dari model ini.
// Password dikelola 100% oleh Firebase Auth. Admin WAJIB me-reset password
// seluruh 30 karyawan melalui Firebase Console (Authentication → Users).
// ====================================================================

import 'package:flutter/material.dart';

class RealEmployeeModel {
  final String nik;
  final String name;
  final String email;
  final String department;
  final String roleTitle;
  final bool isActive;
  final int avatarColorHex;

  // Status Absensi Hari Ini / Berjalan
  final String attendanceStatus; // 'Hadir', 'Terlambat', 'Belum Hadir', 'Cuti'
  final String attendanceTime;
  final String attendanceLocation;
  final int delayMinutes;

  const RealEmployeeModel({
    required this.nik,
    required this.name,
    required this.email,
    required this.department,
    required this.roleTitle,
    this.isActive = true,
    required this.avatarColorHex,
    required this.attendanceStatus,
    required this.attendanceTime,
    required this.attendanceLocation,
    this.delayMinutes = 0,
  });

  Color get avatarColor => Color(avatarColorHex);

  RealEmployeeModel copyWith({
    String? nik,
    String? name,
    String? email,
    String? department,
    String? roleTitle,
    bool? isActive,
    int? avatarColorHex,
    String? attendanceStatus,
    String? attendanceTime,
    String? attendanceLocation,
    int? delayMinutes,
  }) {
    return RealEmployeeModel(
      nik: nik ?? this.nik,
      name: name ?? this.name,
      email: email ?? this.email,
      department: department ?? this.department,
      roleTitle: roleTitle ?? this.roleTitle,
      isActive: isActive ?? this.isActive,
      avatarColorHex: avatarColorHex ?? this.avatarColorHex,
      attendanceStatus: attendanceStatus ?? this.attendanceStatus,
      attendanceTime: attendanceTime ?? this.attendanceTime,
      attendanceLocation: attendanceLocation ?? this.attendanceLocation,
      delayMinutes: delayMinutes ?? this.delayMinutes,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'nik': nik,
      'name': name,
      'email': email,
      'department': department,
      'roleTitle': roleTitle,
      'isActive': isActive,
      'avatarColorHex': avatarColorHex,
      'attendanceStatus': attendanceStatus,
      'attendanceTime': attendanceTime,
      'attendanceLocation': attendanceLocation,
      'delayMinutes': delayMinutes,
    };
  }

  factory RealEmployeeModel.fromJson(Map<String, dynamic> json) {
    return RealEmployeeModel(
      nik: json['nik'] as String? ?? '00000',
      name: json['name'] as String? ?? 'Tanpa Nama',
      email: json['email'] as String? ?? 'email@geosync.co.id',
      department: json['department'] as String? ?? 'General',
      roleTitle: json['roleTitle'] as String? ?? 'Staff',
      isActive: json['isActive'] as bool? ?? true,
      avatarColorHex: json['avatarColorHex'] as int? ?? 0xFF1E3A8A,
      attendanceStatus: json['attendanceStatus'] as String? ?? 'Belum Hadir',
      attendanceTime: json['attendanceTime'] as String? ?? '—',
      attendanceLocation: json['attendanceLocation'] as String? ?? 'Belum ada rekam jejak',
      delayMinutes: json['delayMinutes'] as int? ?? 0,
    );
  }

  // Seed awal 30 Karyawan Realistik dengan jadwal langsung 5 Agustus 2026 - 6 Agustus 2026
  static const List<RealEmployeeModel> initial30Employees = [
    RealEmployeeModel(
      nik: '2026001',
      name: 'Dionisius Pratama',
      email: 'dion.pratama@geosync.co.id',
      department: 'IT Support',
      roleTitle: 'Lead IT Specialist',
      avatarColorHex: 0xFF1B4E6B,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:55 WIB',
      attendanceLocation: 'Head Office (dalam radius 24m)',
    ),
    RealEmployeeModel(
      nik: '2026002',
      name: 'Nadia Maharani',
      email: 'nadia.maharani@geosync.co.id',
      department: 'Finance & Accounting',
      roleTitle: 'Senior Tax Specialist',
      avatarColorHex: 0xFF8DA3E8,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:01 WIB',
      attendanceLocation: 'Head Office (dalam radius 35m)',
    ),
    RealEmployeeModel(
      nik: '2026003',
      name: 'Reza Anugrah',
      email: 'reza.anugrah@geosync.co.id',
      department: 'Operations',
      roleTitle: 'Field Operations Supervisor',
      avatarColorHex: 0xFF009688,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:48 WIB',
      attendanceLocation: 'Branch Bandung (dalam radius 15m)',
    ),
    RealEmployeeModel(
      nik: '2026004',
      name: 'Citra Kirana',
      email: 'citra.kirana@geosync.co.id',
      department: 'HR & GA',
      roleTitle: 'Talent Acquisition Executive',
      avatarColorHex: 0xFFE91E63,
      attendanceStatus: 'Terlambat',
      attendanceTime: '08:42 WIB',
      attendanceLocation: 'Head Office (dalam radius 42m)',
      delayMinutes: 42,
    ),
    RealEmployeeModel(
      nik: '2026005',
      name: 'Bagas Saputra',
      email: 'bagas.saputra@geosync.co.id',
      department: 'Sales & Marketing',
      roleTitle: 'Strategic Key Account Lead',
      avatarColorHex: 0xFFFF9800,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:05 WIB',
      attendanceLocation: 'Site Surabaya (dalam radius 20m)',
    ),
    RealEmployeeModel(
      nik: '2026006',
      name: 'Alyssa Putri',
      email: 'alyssa.putri@geosync.co.id',
      department: 'Customer Service',
      roleTitle: 'Head of Customer Success',
      avatarColorHex: 0xFF9C27B0,
      attendanceStatus: 'Belum Hadir',
      attendanceTime: '—',
      attendanceLocation: 'Belum ada rekam jejak',
    ),
    RealEmployeeModel(
      nik: '2026007',
      name: 'Hendra Gunawan',
      email: 'hendra.gunawan@geosync.co.id',
      department: 'Engineering',
      roleTitle: 'Cloud Systems Architect',
      avatarColorHex: 0xFF3F51B5,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:50 WIB',
      attendanceLocation: 'Head Office (dalam radius 12m)',
    ),
    RealEmployeeModel(
      nik: '2026008',
      name: 'Maya Septiana',
      email: 'maya.septiana@geosync.co.id',
      department: 'Public Relations',
      roleTitle: 'Corporate Communication Specialist',
      avatarColorHex: 0xFF4CAF50,
      attendanceStatus: 'Terlambat',
      attendanceTime: '09:15 WIB',
      attendanceLocation: 'Head Office (dalam radius 62m)',
      delayMinutes: 75,
    ),
    RealEmployeeModel(
      nik: '2026009',
      name: 'Rangga Kurniawan',
      email: 'rangga.kurniawan@geosync.co.id',
      department: 'Logistics',
      roleTitle: 'Supply Chain Analyst',
      avatarColorHex: 0xFF795548,
      attendanceStatus: 'Belum Hadir',
      attendanceTime: '—',
      attendanceLocation: 'Belum ada rekam jejak',
    ),
    RealEmployeeModel(
      nik: '2026010',
      name: 'Laila Anggraini',
      email: 'laila.anggraini@geosync.co.id',
      department: 'Product Management',
      roleTitle: 'Senior Product Owner',
      avatarColorHex: 0xFF607D8B,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:00 WIB',
      attendanceLocation: 'Head Office (dalam radius 10m)',
    ),
    RealEmployeeModel(
      nik: '2026011',
      name: 'Fajar Surya',
      email: 'fajar.surya@geosync.co.id',
      department: 'IT Support',
      roleTitle: 'Network Infrastructure Engineer',
      avatarColorHex: 0xFF1B4E6B,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:45 WIB',
      attendanceLocation: 'Head Office (dalam radius 15m)',
    ),
    RealEmployeeModel(
      nik: '2026012',
      name: 'Karina Wulandari',
      email: 'karina.wulandari@geosync.co.id',
      department: 'Finance & Accounting',
      roleTitle: 'Budget & Treasury Manager',
      avatarColorHex: 0xFFE91E63,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:10 WIB',
      attendanceLocation: 'Head Office (dalam radius 30m)',
    ),
    RealEmployeeModel(
      nik: '2026013',
      name: 'Dimas Anggoro',
      email: 'dimas.anggoro@geosync.co.id',
      department: 'Operations',
      roleTitle: 'Regional Facilities Officer',
      avatarColorHex: 0xFF009688,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:52 WIB',
      attendanceLocation: 'Site Semarang (dalam radius 28m)',
    ),
    RealEmployeeModel(
      nik: '2026014',
      name: 'Tari Puspa',
      email: 'tari.puspa@geosync.co.id',
      department: 'HR & GA',
      roleTitle: 'Employee Relations Generalist',
      avatarColorHex: 0xFF9C27B0,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:03 WIB',
      attendanceLocation: 'Head Office (dalam radius 19m)',
    ),
    RealEmployeeModel(
      nik: '2026015',
      name: 'Satia Hidayat',
      email: 'satia.hidayat@geosync.co.id',
      department: 'Sales & Marketing',
      roleTitle: 'Digital Marketing Lead',
      avatarColorHex: 0xFFFF5722,
      attendanceStatus: 'Terlambat',
      attendanceTime: '08:35 WIB',
      attendanceLocation: 'Head Office (dalam radius 44m)',
      delayMinutes: 35,
    ),
    RealEmployeeModel(
      nik: '2026016',
      name: 'Bella Saphira',
      email: 'bella.saphira@geosync.co.id',
      department: 'Customer Service',
      roleTitle: 'Quality Monitoring Officer',
      avatarColorHex: 0xFF3F51B5,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:00 WIB',
      attendanceLocation: 'Head Office (dalam radius 14m)',
    ),
    RealEmployeeModel(
      nik: '2026017',
      name: 'Aditya Pradana',
      email: 'aditya.pradana@geosync.co.id',
      department: 'Engineering',
      roleTitle: 'Backend Development Team Lead',
      avatarColorHex: 0xFF673AB7,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:58 WIB',
      attendanceLocation: 'Head Office (dalam radius 21m)',
    ),
    RealEmployeeModel(
      nik: '2026018',
      name: 'Risti Pramesti',
      email: 'risti.pramesti@geosync.co.id',
      department: 'Public Relations',
      roleTitle: 'Social Media & Brand Manager',
      avatarColorHex: 0xFF00BCD4,
      attendanceStatus: 'Cuti',
      attendanceTime: '—',
      attendanceLocation: 'Cuti Tahunan (Approved HRD)',
    ),
    RealEmployeeModel(
      nik: '2026019',
      name: 'Yoga Wibowo',
      email: 'yoga.wibowo@geosync.co.id',
      department: 'Logistics',
      roleTitle: 'Fleet Management Coordinator',
      avatarColorHex: 0xFF4CAF50,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:40 WIB',
      attendanceLocation: 'Warehouse Bekasi (dalam radius 18m)',
    ),
    RealEmployeeModel(
      nik: '2026020',
      name: 'Farah Lestari',
      email: 'farah.lestari@geosync.co.id',
      department: 'Product Management',
      roleTitle: 'UX Research Lead',
      avatarColorHex: 0xFF9C27B0,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:08 WIB',
      attendanceLocation: 'Head Office (dalam radius 22m)',
    ),
    RealEmployeeModel(
      nik: '2026021',
      name: 'Gilang Ramadhan',
      email: 'gilang.ramadhan@geosync.co.id',
      department: 'IT Support',
      roleTitle: 'Cyber Security Analyst',
      avatarColorHex: 0xFF1B4E6B,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:02 WIB',
      attendanceLocation: 'Head Office (dalam radius 33m)',
    ),
    RealEmployeeModel(
      nik: '2026022',
      name: 'Siska Meliana',
      email: 'siska.meliana@geosync.co.id',
      department: 'Finance & Accounting',
      roleTitle: 'Financial Reporting Auditor',
      avatarColorHex: 0xFF8DA3E8,
      attendanceStatus: 'Terlambat',
      attendanceTime: '08:50 WIB',
      attendanceLocation: 'Head Office (dalam radius 51m)',
      delayMinutes: 50,
    ),
    RealEmployeeModel(
      nik: '2026023',
      name: 'Doni Kusuma',
      email: 'doni.kusuma@geosync.co.id',
      department: 'Operations',
      roleTitle: 'Safety & HSE Coordinator',
      avatarColorHex: 0xFF009688,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:35 WIB',
      attendanceLocation: 'Site Surabaya (dalam radius 11m)',
    ),
    RealEmployeeModel(
      nik: '2026024',
      name: 'Indah Permatasari',
      email: 'indah.permatasari@geosync.co.id',
      department: 'HR & GA',
      roleTitle: 'Compensation & Benefit Specialist',
      avatarColorHex: 0xFFE91E63,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:55 WIB',
      attendanceLocation: 'Head Office (dalam radius 15m)',
    ),
    RealEmployeeModel(
      nik: '2026025',
      name: 'Bayu Skak',
      email: 'bayu.skak@geosync.co.id',
      department: 'Sales & Marketing',
      roleTitle: 'Brand Partnership Manager',
      avatarColorHex: 0xFFFF9800,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:12 WIB',
      attendanceLocation: 'Head Office (dalam radius 25m)',
    ),
    RealEmployeeModel(
      nik: '2026026',
      name: 'Melinda Putri',
      email: 'melinda.putri@geosync.co.id',
      department: 'Customer Service',
      roleTitle: 'Client Support Executive',
      avatarColorHex: 0xFF9C27B0,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:04 WIB',
      attendanceLocation: 'Head Office (dalam radius 30m)',
    ),
    RealEmployeeModel(
      nik: '2026027',
      name: 'Kevin Julio',
      email: 'kevin.julio@geosync.co.id',
      department: 'Engineering',
      roleTitle: 'Mobile Flutter Developer',
      avatarColorHex: 0xFF3F51B5,
      attendanceStatus: 'Terlambat',
      attendanceTime: '09:05 WIB',
      attendanceLocation: 'Head Office (dalam radius 29m)',
      delayMinutes: 65,
    ),
    RealEmployeeModel(
      nik: '2026028',
      name: 'Devi Shanthi',
      email: 'devi.shanthi@geosync.co.id',
      department: 'Legal',
      roleTitle: 'Legal Counsel Executive',
      avatarColorHex: 0xFF795548,
      attendanceStatus: 'Hadir',
      attendanceTime: '08:00 WIB',
      attendanceLocation: 'Head Office (dalam radius 16m)',
    ),
    RealEmployeeModel(
      nik: '2026029',
      name: 'Bambang Pamungkas',
      email: 'bambang.pamungkas@geosync.co.id',
      department: 'Logistics',
      roleTitle: 'Warehouse Supervisor',
      avatarColorHex: 0xFF607D8B,
      attendanceStatus: 'Hadir',
      attendanceTime: '07:30 WIB',
      attendanceLocation: 'Warehouse Bekasi (dalam radius 12m)',
    ),
    RealEmployeeModel(
      nik: '2026030',
      name: 'Annisa Rahma',
      email: 'annisa.rahma@geosync.co.id',
      department: 'Quality Assurance',
      roleTitle: 'QA Lead Automation',
      avatarColorHex: 0xFF4CAF50,
      attendanceStatus: 'Belum Hadir',
      attendanceTime: '—',
      attendanceLocation: 'Belum ada rekam jejak',
    ),
  ];
}
