// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjt85bpKeGG_vK--u3ZwYBEhS2sdQYsHo',
    appId: '1:123710732937:web:78d78cbc790239b5a22458',
    messagingSenderId: '123710732937',
    projectId: 'geosync-f8647',
    authDomain: 'geosync-f8647.firebaseapp.com',
    storageBucket: 'geosync-f8647.firebasestorage.app',
    measurementId: 'G-KHZSVRH7BN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfYHJFvfQrvvHp_omW-CZQeX0CitBu-NI',
    appId: '1:123710732937:android:59bef0da76caebf7a22458',
    messagingSenderId: '123710732937',
    projectId: 'geosync-f8647',
    storageBucket: 'geosync-f8647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwKCVku4dEW58Cs4A4Saj4qycBZwXoaI',
    appId: '1:123710732937:ios:e5c55d2b3a60b24aa22458',
    messagingSenderId: '123710732937',
    projectId: 'geosync-f8647',
    storageBucket: 'geosync-f8647.firebasestorage.app',
    iosBundleId: 'com.geosync.geosync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwKCVku4dEW58Cs4A4Saj4qycBZwXoaI',
    appId: '1:123710732937:ios:e5c55d2b3a60b24aa22458',
    messagingSenderId: '123710732937',
    projectId: 'geosync-f8647',
    storageBucket: 'geosync-f8647.firebasestorage.app',
    iosBundleId: 'com.geosync.geosync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjt85bpKeGG_vK--u3ZwYBEhS2sdQYsHo',
    appId: '1:123710732937:web:1afcaedd6928d8c4a22458',
    messagingSenderId: '123710732937',
    projectId: 'geosync-f8647',
    authDomain: 'geosync-f8647.firebaseapp.com',
    storageBucket: 'geosync-f8647.firebasestorage.app',
    measurementId: 'G-2KGQYVBLRV',
  );
}
